# Generated by Django 4.0.5 on 2022-07-17 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=50)),
                ('package_price', models.CharField(max_length=50)),
                ('customer', models.ManyToManyField(to='user.customer')),
            ],
        ),
    ]
